project_id = "vlfauqpgkyaggxuwtqmp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.secure-api]
verify_jwt = true