// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlfauqpgkyaggxuwtqmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZmF1cXBna3lhZ2d4dXd0cW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTU2NjUsImV4cCI6MjA2NzAzMTY2NX0.KtVTr1_v0MADYJcUOSvvg8dfUpfESg-S0MCb7S8incE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});